version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ateste_me_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d ateste_me_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - polls_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  polls_pg_data:
